# AUTO-GENERATED BY AI TEST GENERATOR
# Feature: User should be able to log in with valid credentials
# Generated by: generate_tests.py

import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service


class LoginPage:
    """Page Object for Login Page"""

    def __init__(self, driver):
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)
        self.username_input = (By.ID, "user-name")
        self.password_input = (By.ID, "password")
        self.login_button   = (By.ID, "login-button")
        self.error_message  = (By.CSS_SELECTOR, "[data-test='error']")

    def enter_username(self, username):
        field = self.wait.until(EC.presence_of_element_located(self.username_input))
        field.clear()
        field.send_keys(username)

    def enter_password(self, password):
        field = self.wait.until(EC.presence_of_element_located(self.password_input))
        field.clear()
        field.send_keys(password)

    def click_login(self):
        self.wait.until(EC.element_to_be_clickable(self.login_button)).click()

    def get_error_message(self):
        return self.wait.until(
            EC.presence_of_element_located(self.error_message)
        ).text


@pytest.fixture
def driver():
    """Setup and teardown Chrome WebDriver"""
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    driver.maximize_window()
    yield driver
    driver.quit()


class TestLogin:

    def test_valid_login(self, driver):
        """Test that valid user can log in successfully"""
        driver.get("https://www.saucedemo.com")
        login_page = LoginPage(driver)

        login_page.enter_username("standard_user")
        login_page.enter_password("secret_sauce")
        login_page.click_login()

        # Assert user is redirected to inventory page
        wait = WebDriverWait(driver, 10)
        wait.until(EC.url_contains("inventory"))
        assert "inventory" in driver.current_url, "Login failed — not redirected to inventory page"

    def test_invalid_login(self, driver):
        """Test that invalid credentials show error message"""
        driver.get("https://www.saucedemo.com")
        login_page = LoginPage(driver)

        login_page.enter_username("wrong_user")
        login_page.enter_password("wrong_password")
        login_page.click_login()

        error = login_page.get_error_message()
        assert "Username and password do not match" in error

    def test_locked_out_user(self, driver):
        """Test that locked out user sees appropriate error"""
        driver.get("https://www.saucedemo.com")
        login_page = LoginPage(driver)

        login_page.enter_username("locked_out_user")
        login_page.enter_password("secret_sauce")
        login_page.click_login()

        error = login_page.get_error_message()
        assert "locked out" in error
